// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package billeterie.proxies;

public class Panier
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject panierMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Billeterie.Panier";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Panier_Billet("Billeterie.Panier_Billet");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Panier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Billeterie.Panier"));
	}

	protected Panier(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject panierMendixObject)
	{
		if (panierMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Billeterie.Panier", panierMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Billeterie.Panier");

		this.panierMendixObject = panierMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Panier.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static billeterie.proxies.Panier initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return billeterie.proxies.Panier.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static billeterie.proxies.Panier initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new billeterie.proxies.Panier(context, mendixObject);
	}

	public static billeterie.proxies.Panier load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return billeterie.proxies.Panier.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Panier_Billet
	 */
	public final java.util.List<billeterie.proxies.Billet> getPanier_Billet() throws com.mendix.core.CoreException
	{
		return getPanier_Billet(getContext());
	}

	/**
	 * @param context
	 * @return value of Panier_Billet
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<billeterie.proxies.Billet> getPanier_Billet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<billeterie.proxies.Billet> result = new java.util.ArrayList<billeterie.proxies.Billet>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Panier_Billet.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(billeterie.proxies.Billet.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Panier_Billet
	 * @param panier_billet
	 */
	public final void setPanier_Billet(java.util.List<billeterie.proxies.Billet> panier_billet)
	{
		setPanier_Billet(getContext(), panier_billet);
	}

	/**
	 * Set value of Panier_Billet
	 * @param context
	 * @param panier_billet
	 */
	public final void setPanier_Billet(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<billeterie.proxies.Billet> panier_billet)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (billeterie.proxies.Billet proxyObject : panier_billet)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Panier_Billet.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return panierMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final billeterie.proxies.Panier that = (billeterie.proxies.Panier) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Billeterie.Panier";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
