// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package billeterie.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Billeterie module
	public static void ajoutPanier(IContext context, billeterie.proxies.Billet _billet, billeterie.proxies.Panier _panier)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Billet", _billet == null ? null : _billet.getMendixObject());
		params.put("Panier", _panier == null ? null : _panier.getMendixObject());
		Core.microflowCall("Billeterie.ajoutPanier").withParams(params).execute(context);
	}
	public static java.math.BigDecimal calculTTC(IContext context, billeterie.proxies.Billet _entity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Entity", _entity == null ? null : _entity.getMendixObject());
		return (java.math.BigDecimal) Core.microflowCall("Billeterie.calculTTC").withParams(params).execute(context);
	}
	public static billeterie.proxies.Panier instancePanier(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Billeterie.InstancePanier").withParams(params).execute(context);
		return result == null ? null : billeterie.proxies.Panier.initialize(context, result);
	}
}